//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BancoDoceriaContainer : DbContext
    {
        public BancoDoceriaContainer()
            : base("name=BancoDoceriaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DoceSabor> DoceSaborSet { get; set; }
        public virtual DbSet<DoceTipo> DoceTipoSet { get; set; }
        public virtual DbSet<DoceAdicional> DoceAdicionalSet { get; set; }
        public virtual DbSet<Pedido> PedidoSet { get; set; }
    }
}
