//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoceSabor
    {
        public int IdSabor { get; set; }
        public double ValorSabor { get; set; }
        public string NomeSabor { get; set; }
    
        public virtual Pedido Pedidos { get; set; }
    }
}
