//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoceTipo
    {
        public int IdTipo { get; set; }
        public double ValorTipo { get; set; }
        public string NomeTipo { get; set; }
    
        public virtual Pedido Pedidos { get; set; }
    }
}
